image: docker:20.10.17

services:
  - docker:20.10.17-dind

stages:
  - build
  - package
  - deploy

build:
  image: maven:3.8.5-sapmachine-17
  tags:
    - progreso
  stage: build
  cache:
    paths:
      - .m2/repository
    when: 'on_success'
    key: "$CI_JOB_NAME"
  script:
    - mvn clean package
  artifacts:
    paths:
      - target
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

package:
  stage: package
  tags:
    - progreso
  variables:
    IMAGE_FULL_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    IMAGE_LATEST_NAME: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_FULL_NAME -t $IMAGE_LATEST_NAME .
    - docker push $IMAGE_FULL_NAME
    - docker push $IMAGE_LATEST_NAME
  only:
    - develop

deploy:
  stage: deploy
  tags:
    - progreso
  only:
    - develop
  before_script:
    - chmod 400 $SERVER_PRIVATE_SSH_KEY
  script:
    - apk upgrade && apk update && apk add openssh-client
    - ssh -o StrictHostKeyChecking=no -i $SERVER_PRIVATE_SSH_KEY $SERVER_USER@host.docker.internal "cd progreso-devops && git pull && docker compose up -d --force-recreate java-gateway-dev"

